name: GitHub Actions Demo
on: [push]
#on:
#    push:
#        branches:
#            - master
jobs:
  Explore-GitHub-Actions:
    #runs-on: [self-hosted, pjuarez]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.name }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo  "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
  
      - run: echo "ğŸ–¥ï¸ running Terraform init."
      - name: Terraform  init
       
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
            TF_ACTION_WORKING_DIR: 'terraform'
            TF_VAR_fingerprint:  ${{ secrets.API_FINGERPRINT }}
            TF_VAR_user_ocid:  ${{ secrets.USER_ID }}
            TF_VAR_region: ${{ secrets.REGION}}
            
     # - name: Terraform Validate
     #   id: validate
     #   run: terraform validate -no-color

     # - name: Terraform Plan
     #   id: plan
     #   run: terraform plan -no-color

