
name: lint ansible playbook

on:
  pull_request:
    branches: 
      - main 

jobs:

  LintAnsible:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Run ansible-lint
      uses: ansible-community/ansible-lint-action@v6
      # optional:
      with:
        targets: "./ansible/playbook.yaml" 
